"""initial_schema

Revision ID: 82c9d1856ea0
Revises: 
Create Date: 2026-06-08 21:05:42.394261
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '82c9d1856ea0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=16), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('crop_strategy', sa.String(length=32), nullable=True),
    sa.Column('codec', sa.String(length=32), nullable=True),
    sa.Column('bitrate', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('format_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('project_version', sa.Integer(), nullable=True),
    sa.Column('analysis_config_snapshot', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_path')
    )
    op.create_table('schema_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dynamic_level', sa.String(length=32), nullable=True),
    sa.Column('preset_version', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preset_id')
    )
    op.create_table('manual_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source_rel_path', sa.String(length=1024), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('analyzed_at', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('analyzed_at', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'rel_path')
    )
    op.create_table('timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.String(length=64), nullable=True),
    sa.Column('format_id', sa.String(length=64), nullable=True),
    sa.Column('target_duration_s', sa.Float(), nullable=True),
    sa.Column('actual_duration_s', sa.Float(), nullable=True),
    sa.Column('variant_id', sa.String(length=4), nullable=True),
    sa.Column('seed_offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('render_config_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_beat_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_audio_id', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('beat_times', sa.JSON(), nullable=True),
    sa.Column('beat_strengths', sa.JSON(), nullable=True),
    sa.Column('strong_beats', sa.JSON(), nullable=True),
    sa.Column('onset_times', sa.JSON(), nullable=True),
    sa.Column('beat_clarity', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_audio_id'], ['source_audios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_audio_id', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=True),
    sa.Column('end_s', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('section_type', sa.String(length=32), nullable=True),
    sa.Column('energy_score', sa.Float(), nullable=True),
    sa.Column('rhythm_score', sa.Float(), nullable=True),
    sa.Column('montage_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('selected_by_system', sa.Boolean(), nullable=True),
    sa.Column('selected_by_user', sa.Integer(), nullable=True),
    sa.Column('excluded_by_user', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_audio_id'], ['source_audios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('render_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('preset_id', sa.String(length=64), nullable=True),
    sa.Column('format_id', sa.String(length=64), nullable=True),
    sa.Column('target_duration_s', sa.Float(), nullable=True),
    sa.Column('actual_duration_s', sa.Float(), nullable=True),
    sa.Column('clip_count', sa.Integer(), nullable=True),
    sa.Column('quality_avg', sa.Float(), nullable=True),
    sa.Column('variant_id', sa.String(length=4), nullable=True),
    sa.Column('is_preview', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('render_config_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_video_id', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_video_rel_path', sa.String(length=1024), nullable=True),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('aesthetic_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('style_scores', sa.JSON(), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('user_approved', sa.Integer(), nullable=True),
    sa.Column('user_priority', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_rel_path', sa.String(length=1024), nullable=True),
    sa.Column('preview_rel_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('render_job_id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=True),
    sa.Column('format_id', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['render_job_id'], ['render_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('sharpness', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('noise_level', sa.Float(), nullable=True),
    sa.Column('colorfulness', sa.Float(), nullable=True),
    sa.Column('saturation', sa.Float(), nullable=True),
    sa.Column('motion_magnitude', sa.Float(), nullable=True),
    sa.Column('camera_shake', sa.Float(), nullable=True),
    sa.Column('camera_motion_type', sa.String(length=32), nullable=True),
    sa.Column('optical_flow_mean', sa.Float(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('face_size_ratio', sa.Float(), nullable=True),
    sa.Column('person_count', sa.Integer(), nullable=True),
    sa.Column('has_face', sa.Boolean(), nullable=True),
    sa.Column('has_person', sa.Boolean(), nullable=True),
    sa.Column('composition_score', sa.Float(), nullable=True),
    sa.Column('saliency_score', sa.Float(), nullable=True),
    sa.Column('rule_of_thirds_score', sa.Float(), nullable=True),
    sa.Column('aesthetic_score', sa.Float(), nullable=True),
    sa.Column('scene_type', sa.String(length=32), nullable=True),
    sa.Column('scene_tags', sa.JSON(), nullable=True),
    sa.Column('primary_scene_tag', sa.String(length=64), nullable=True),
    sa.Column('is_blurry', sa.Boolean(), nullable=True),
    sa.Column('is_shaky', sa.Boolean(), nullable=True),
    sa.Column('is_dark', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('reject_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id')
    )
    op.create_table('render_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('render_job_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('liked_segments', sa.JSON(), nullable=True),
    sa.Column('disliked_segments', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['render_job_id'], ['render_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('shot_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('transition_type', sa.String(length=32), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('is_beat_aligned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['timeline_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id_a', sa.Integer(), nullable=False),
    sa.Column('candidate_id_b', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id_a'], ['clip_candidates.id'], ),
    sa.ForeignKeyConstraint(['candidate_id_b'], ['clip_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplicates')
    op.drop_table('transitions')
    op.drop_table('shots')
    op.drop_table('render_feedback')
    op.drop_table('quality_metrics')
    op.drop_table('export_files')
    op.drop_table('clip_candidates')
    op.drop_table('timeline_segments')
    op.drop_table('scenes')
    op.drop_table('render_jobs')
    op.drop_table('music_sections')
    op.drop_table('audio_beat_maps')
    op.drop_table('timelines')
    op.drop_table('source_videos')
    op.drop_table('source_audios')
    op.drop_table('manual_selections')
    op.drop_table('style_presets')
    op.drop_table('schema_version')
    op.drop_table('projects')
    op.drop_table('output_formats')
    # ### end Alembic commands ###
