"""video_intelligence_layer

Revision ID: 9c9cb49f2472
Revises: 82c9d1856ea0
Create Date: 2026-06-09 08:41:40.829639
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9c9cb49f2472'
down_revision: Union[str, None] = '82c9d1856ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('analysis_type', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('source_rel_path', sa.String(length=1024), nullable=True),
    sa.Column('start_s', sa.Float(), nullable=True),
    sa.Column('end_s', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('result_blob_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('video_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('concept_type', sa.String(length=64), nullable=True),
    sa.Column('narrative_arc', sa.String(length=64), nullable=True),
    sa.Column('dominant_tags', sa.JSON(), nullable=True),
    sa.Column('energy_profile', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_feature_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('camera_motion_type', sa.String(length=64), nullable=True),
    sa.Column('camera_motion_confidence', sa.Float(), nullable=True),
    sa.Column('camera_motion_speed', sa.String(length=16), nullable=True),
    sa.Column('eye_state', sa.String(length=16), nullable=True),
    sa.Column('pose_type', sa.String(length=32), nullable=True),
    sa.Column('body_crop_quality', sa.Float(), nullable=True),
    sa.Column('human_frame_quality', sa.Float(), nullable=True),
    sa.Column('semantic_tags', sa.JSON(), nullable=True),
    sa.Column('primary_semantic_tag', sa.String(length=64), nullable=True),
    sa.Column('scene_context', sa.String(length=64), nullable=True),
    sa.Column('face_sharpness', sa.Float(), nullable=True),
    sa.Column('motion_blur_score', sa.Float(), nullable=True),
    sa.Column('exposure_score', sa.Float(), nullable=True),
    sa.Column('noise_score', sa.Float(), nullable=True),
    sa.Column('horizon_level', sa.Float(), nullable=True),
    sa.Column('suggested_role', sa.String(length=16), nullable=True),
    sa.Column('role_confidence', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['clip_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('segment_style_fits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('style_preset_id', sa.String(length=64), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('motion_fit', sa.Float(), nullable=True),
    sa.Column('semantic_fit', sa.Float(), nullable=True),
    sa.Column('role_fit', sa.Float(), nullable=True),
    sa.Column('quality_fit', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['clip_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'style_preset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_style_fits')
    op.drop_table('segment_feature_profiles')
    op.drop_table('video_concepts')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
